FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Anagrams

API to return all posibla combinations of letters for a provided word

## Anagram [/anagram{?word}]

### GET Anagrams [GET]

+ Parameters
    
    + word: kliment (String)

+ Response 200 (application/json)

    + Attributes (Anagrams)



# Data Structures

# Input String (string)

## Sample

kliment

# Anagrams (array[Anagram])

# Anagram (string)

## Sample

netmilk